kind: Service
apiVersion: v1
metadata:
  name: nginx-for-6-2
  labels:
    app: nginx-for-6-2
    app.kubernetes.io/component: nginx-for-6-2
    app.kubernetes.io/part-of: nginx-for-6-2
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: nginx-for-6-2
    deployment: nginx-for-6-2